[build]
base = "/"
command = "npm ci && npm run build"
publish = "dist"

[build.environment]
PYTHON_VERSION = "3.9"
NODE_VERSION = "18"
NPM_FLAGS = "--no-optional"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
