[build]
base = "/campus-pharmacy-main"
command = "cd campus-pharmacy-main && npm install && npm run build"
publish = "campus-pharmacy-main/dist"

[build.environment]
PYTHON_VERSION = "3.9"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
