[build]
base = "/"
command = "npm install && npm run build"
publish = "dist"

[build.environment]
PYTHON_VERSION = "3.9"
NODE_VERSION = "18"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
